[
    "Argentine",
    "France",
    "Brésil",
    "Angleterre",
    "Belgique",
    "Croatie",
    "Pays-Bas",
    "Portugal",
    "Italie",
    "Espagne",
    "États-Unis",
    "Mexique",
    "Maroc",
    "Suisse",
    "Allemagne",
    "Colombie",
    "Uruguay",
    "Danemark",
    "Japon",
    "Sénégal",
    "RI Iran",
    "Pérou",
    "Suède",
    "Ukraine",
    "Autriche",
    "République de Corée",
    "Australie",
    "Serbie",
    "Tunisie",
    "Pologne",
    "Écosse",
    "Hongrie",
    "Pays de Galles",
    "Algérie",
    "Égypte",
    "Chili",
    "République tchèque",
    "Équateur",
    "Russie",
    "Nigeria",
    "Cameroun",
    "Turquie",
    "Norvège",
    "Canada",
    "Panamá",
    "Costa Rica",
    "Roumanie",
    "Slovaquie",
    "Mali",
    "Côte d'Ivoire",
    "Grèce",
    "Paraguay",
    "Venezuela",
    "Finlande",
    "République d’Irlande",
    "Jamaïque",
    "Arabie saoudite",
    "Burkina Faso",
    "Slovénie",
    "Ghana",
    "Qatar",
    "Albanie",
    "Bosnie-et-Herzégovine",
    "RD Congo",
    "Afrique du Sud",
    "Macédoine du Nord",
    "Islande",
    "Monténégro",
    "Irak",
    "Émirats arabes unis",
    "Cap-Vert",
    "Israël",
    "Oman",
    "Irlande du Nord",
    "Ouzbékistan",
    "Salvador",
    "Honduras",
    "Bulgarie",
    "Géorgie",
    "RP Chine",
    "Guinée",
    "Zambie",
    "Bolivie",
    "Jordanie",
    "Luxembourg",
    "Bahreïn",
    "Haïti",
    "Gabon",
    "Ouganda",
    "Curaçao",
    "Arménie",
    "Guinée équatoriale",
    "Syrie",
    "Bénin",
    "Vietnam",
    "République kirghize",
    "Palestine",
    "Trinité-et-Tobago",
    "Mauritanie",
    "Kazakhstan",
    "Liban",
    "Inde",
    "Guatemala",
    "Aotearoa Nouvelle-Zélande",
    "Belarus",
    "Guinée-Bissau",
    "Congo",
    "Madagascar",
    "Kenya",
    "Tadjikistan",
    "Kosovo",
    "Thaïlande",
    "Mozambique",
    "Namibie",
    "Estonie",
    "RDP Corée",
    "Angola",
    "Gambie",
    "Togo",
    "Chypre",
    "Azerbaïdjan",
    "Tanzanie",
    "Malawi",
    "Sierra Leone",
    "Zimbabwe",
    "Libye",
    "République centrafricaine",
    "Niger",
    "Comores",
    "Soudan",
    "Îles Féroé",
    "Philippines",
    "Îles Salomon",
    "Malaisie",
    "Koweït",
    "Lettonie",
    "Antigua-et-Barbuda",
    "Nicaragua",
    "Rwanda",
    "Turkménistan",
    "Burundi",
    "Éthiopie",
    "Lituanie",
    "Eswatini",
    "Suriname",
    "Saint-Kitts-et-Nevis",
    "Indonésie",
    "Hong Kong, Chine",
    "Botswana",
    "Liberia",
    "République dominicaine",
    "Lesotho",
    "Andorre",
    "Chinese Taipei",
    "Maldives",
    "Yémen",
    "Singapour",
    "Afghanistan",
    "Moldavie",
    "Porto Rico",
    "Myanmar",
    "Papouasie-Nouvelle-Guinée",
    "Nouvelle-Calédonie",
    "Tahiti",
    "Guyana",
    "Sainte-Lucie",
    "Soudan du Sud",
    "Vanuatu",
    "Cuba",
    "Fidji",
    "Malte",
    "Barbade",
    "Grenade",
    "Bermudes",
    "Népal",
    "Saint-Vincent-et-les-Grenadines",
    "Cambodge",
    "Maurice",
    "Montserrat",
    "Belize",
    "Tchad",
    "Dominique",
    "Mongolie",
    "Bhoutan",
    "Macao",
    "Laos",
    "Îles Cook",
    "São Tomé-et-Príncipe",
    "Bangladesh",
    "Djibouti",
    "Brunei",
    "Timor oriental",
    "Aruba",
    "Somalie",
    "Seychelles",
    "Îles Caïmans",
    "Pakistan",
    "Gibraltar",
    "Liechtenstein",
    "Bahamas",
    "Guam",
    "Sri Lanka",
    "Turks-et-Caicos",
    "Îles Vierges américaines",
    "Îles Vierges britanniques",
    "Anguilla",
    "Saint-Marin"
]